# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        gem install bundler
        bundle install --retry=3 --jobs=4
    displayName: 'Install dependencies'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'bundle exec rake ci || true'
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test*.xml'
      failTaskOnFailedTests: true
    displayName: 'Verify and publish test results'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'gem build *.gemspec'
    displayName: 'Build gem file'

  - task: CopyFiles@2
    inputs:
      contents: '*.gem'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy gem file'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'fastlane-plugin-gem'
    displayName: 'Publish gem file as AzDO artifact'
